-- Daily Tenders and Saved Tenders. Same columns.
-- String columns are unbounded varchar (PostgreSQL text).
-- Json columns are jsonb. Date columns are date, not timestamp.

CREATE TABLE IF NOT EXISTS "DailyTenders" (
    "id"                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "portalLink"        TEXT    NOT NULL,
    "ePublishedDate"    DATE    NOT NULL,
    "closingDate"       DATE    NOT NULL,
    "openingDate"       DATE    NOT NULL,
    "titleAndRefNo"     TEXT    NOT NULL,
    "tenderId"          TEXT    NOT NULL,
    "organisationChain" BIGINT  NOT NULL,
    "tenderDetails"     JSONB   NOT NULL,
    "emdAmount"         BIGINT  NOT NULL,
    "emdDoc"            JSONB,
    "emdDate"           DATE,
    "emdMoneyOffice"    TEXT,
    "preQualification"  TEXT    NOT NULL,
    "tenderValue"       BIGINT  NOT NULL,
    "productCategory"   TEXT    NOT NULL,
    "tenderDocs"        JSONB   NOT NULL,
    "sdMoney"           BIGINT,
    "sdDocs"            JSONB,
    "sdIssueDate"       DATE,
    "sdExpireDate"      DATE,
    "sdMoneyOffice"     TEXT,
    "corrigendum"       JSONB   NOT NULL,
    "subCategory"       TEXT    NOT NULL,
    "tAck"              JSONB   NOT NULL,
    "isWin"             BOOLEAN NOT NULL,

    CONSTRAINT "DailyTenders_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "SavedTenders" (
    "id"                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "portalLink"        TEXT    NOT NULL,
    "ePublishedDate"    DATE    NOT NULL,
    "closingDate"       DATE    NOT NULL,
    "openingDate"       DATE    NOT NULL,
    "titleAndRefNo"     TEXT    NOT NULL,
    "tenderId"          TEXT    NOT NULL,
    "organisationChain" BIGINT  NOT NULL,
    "tenderDetails"     JSONB   NOT NULL,
    "emdAmount"         BIGINT  NOT NULL,
    "emdDoc"            JSONB,
    "emdDate"           DATE,
    "emdMoneyOffice"    TEXT,
    "preQualification"  TEXT    NOT NULL,
    "tenderValue"       BIGINT  NOT NULL,
    "productCategory"   TEXT    NOT NULL,
    "tenderDocs"        JSONB   NOT NULL,
    "sdMoney"           BIGINT,
    "sdDocs"            JSONB,
    "sdIssueDate"       DATE,
    "sdExpireDate"      DATE,
    "sdMoneyOffice"     TEXT,
    "corrigendum"       JSONB   NOT NULL,
    "subCategory"       TEXT    NOT NULL,
    "tAck"              JSONB   NOT NULL,
    "isWin"             BOOLEAN NOT NULL,

    CONSTRAINT "SavedTenders_pkey" PRIMARY KEY ("id")
);
